display_name: Bangla Keyboard
package_name: bangla-keyboard
version: 1.0.0
version_code: 1
architecture: amd64
maintainer:
  name: Soumen Bar
  email: your.email@example.com
priority: optional
section: utils
essential: false
icon: assets/keyboard.png
generic_name: Keyboard Application
description: A native Bangla keyboard application built with Flutter.
synopsis: Bangla input utility
installed_size: 1024
categories:
  - Utility
